name: CriLisCraftRankUtils
version: 1.0.1
main: com.criliscraft.rankutils.CriLisCraft
description: This plugin manages ranks on the CriLis Craft Survival server.
author: Chaka
website: http://criliscraft.noip.me/
commands:
  rank:
    description: This command handles all rank changes.
    usage: /<command>
  givepet:
    description: Gives a player a pet.
    usage: /<command>